services:
  app:
      image: ghcr.io/minhvo2005/portfolio:latest
      ports:
        - "3000:3000"
      environment:
        DATABASE_URL: postgres://portfolio:portfolio@db:5432/portfolio
      depends_on:
        db:
          condition: service_healthy
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U portfolio -d portfolio"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  postgres_data:
